# Generated by Django 5.0.2 on 2024-02-17 20:09

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.auth.models import User


def forwards_func(apps, schema_editor):
    Wallet = apps.get_model("b2btask", "Wallet")
    Transaction = apps.get_model("b2btask", "Transaction")
    db_alias = schema_editor.connection.alias
    for i in range(1, 11):
        wallet = Wallet.objects.using(db_alias).create(label=f"test_wallet_{i}")
        balance = 0
        for j in range(1, 6):
            Transaction.objects.using(db_alias).create(
                txid=f"test_transaction_{j}_wallet_{i}", amount=j, wallet_id=wallet.id
            )
            balance += j
        wallet.balance = balance
        wallet.save()

    user = User.objects.create(username="user_0", is_staff=True)
    user.set_password("user_0")
    user.save()


def reverse_func(apps, schema_editor):
    Wallet = apps.get_model("myapp", "Wallet")
    Transaction = apps.get_model("b2btask", "Transaction")
    db_alias = schema_editor.connection.alias
    Wallet.objects.using(db_alias).delete()
    Transaction.objects.using(db_alias).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "balance",
                    models.DecimalField(decimal_places=18, default=0, max_digits=36),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txid", models.CharField(max_length=255, unique=True)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=36)),
                (
                    "wallet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="b2btask.wallet",
                    ),
                ),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
